// ---------------------------------------------------------------------------
// Crew manifest → Excel export for the Greek e-Charterparty (e-Ναυλοσύμφωνο)
// system operated by the Ministry of Maritime Affairs & Insular Policy (ΥΝΑΝΠ).
//
// The authority has NO public API and NO sandbox: the compliant path is to
// upload the persons-on-board list through the portal's "Import from Excel"
// feature. This module builds that workbook from an existing BlueOne charter's
// crew preparation.
//
// NOTE: This is a DRAFT layout. The exact column set / order of the official
// import template can only be confirmed from inside the logged-in portal
// (echarterparty.yna.gov.gr) or its user manual. Reconcile the MANIFEST_COLUMNS
// below with that template before relying on the file for a real submission.
// ---------------------------------------------------------------------------

import type { Charter } from './availability';
import type { ClientPreparation, ManifestGuest } from './clientSpace';
import { manifestGuests } from './clientSpace';
import { getMarinaById } from '../app/marinas-data';
import { buildXlsxBlob, type XlsxSheet } from './xlsx';

const DEFAULT_VESSEL = 'BlueOne — Fountaine Pajot Aura 51';

// Draft column order for the persons-on-board sheet.
export const MANIFEST_COLUMNS = [
  'No.',
  'Last Name / Surname',
  'First Name',
  'Gender',
  'Date of Birth (DD/MM/YYYY)',
  'Nationality',
  'Passport / ID No.',
  'Role',
  'Embarkation Port',
  'Embarkation Date (DD/MM/YYYY)',
  'Disembarkation Port',
  'Disembarkation Date (DD/MM/YYYY)',
] as const;

// 'YYYY-MM-DD' -> 'DD/MM/YYYY' (the format the Greek portal expects).
function fmtDMY(iso?: string): string {
  if (!iso) return '';
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(iso);
  return m ? `${m[3]}/${m[2]}/${m[1]}` : iso;
}

function marinaName(id?: string): string {
  if (!id) return '';
  return getMarinaById(id)?.name ?? id;
}

function guestLastName(g: ManifestGuest): string {
  return g.member.lastName?.trim() || '';
}

function guestFirstName(g: ManifestGuest): string {
  return g.member.firstName?.trim() || `Passenger ${g.index + 1}`;
}

// ---------------------------------------------------------------------------
// Sheet builders
// ---------------------------------------------------------------------------

function personsSheet(charter: Charter, prep: ClientPreparation): XlsxSheet {
  const guests = manifestGuests(charter, prep);
  const embarkFallback = marinaName(charter.deliveryPoint ?? undefined);
  const disembarkFallback = marinaName(
    charter.redeliveryPoint ?? charter.deliveryPoint ?? undefined,
  );

  const rows: (string | number)[][] = [[...MANIFEST_COLUMNS]];

  guests.forEach((g, i) => {
    rows.push([
      i + 1,
      guestLastName(g),
      guestFirstName(g),
      g.member.gender ?? '',
      fmtDMY(g.member.dateOfBirth),
      g.member.nationality ?? '',
      g.member.passportNumber ?? '',
      'Passenger',
      marinaName(g.embarkationPoint) || embarkFallback,
      fmtDMY(g.arrivalDate),
      marinaName(g.disembarkationPoint) || disembarkFallback,
      fmtDMY(g.departureDate),
    ]);
  });

  return { name: 'Persons On Board', rows, headerRow: true };
}

function charterInfoSheet(charter: Charter, prep: ClientPreparation): XlsxSheet {
  const guests = manifestGuests(charter, prep);
  const generated = fmtDMY(new Date().toISOString().slice(0, 10));

  const rows: (string | number)[][] = [
    ['Field', 'Value'],
    ['Vessel', charter.boat || DEFAULT_VESSEL],
    ['Charter Reference', charter.name ?? ''],
    ['Charter Start', fmtDMY(charter.startDate)],
    ['Charter End', fmtDMY(charter.endDate)],
    ['Embarkation (Delivery)', marinaName(charter.deliveryPoint ?? undefined)],
    [
      'Disembarkation (Redelivery)',
      marinaName(charter.redeliveryPoint ?? charter.deliveryPoint ?? undefined),
    ],
    ['Total Persons On Board', guests.length],
    ['Generated', generated],
  ];

  return { name: 'Charter Details', rows, headerRow: true };
}

function instructionsSheet(): XlsxSheet {
  const lines = [
    'e-Ναυλοσύμφωνο (e-Charterparty) — Crew Manifest Export',
    '',
    'This workbook is a DRAFT persons-on-board list generated by BlueOne for',
    'upload to the Greek e-Charterparty portal (echarterparty.yna.gov.gr) via',
    'its "Import from Excel" feature.',
    '',
    'Before submitting:',
    '1. Confirm the column set and order against the official import template',
    '   downloaded from the logged-in portal — this draft may differ.',
    '2. Dates use the DD/MM/YYYY format.',
    '3. Nationality should be entered per the portal\'s accepted list/ISO codes.',
    '4. All persons here are guests (Role = Passenger). Add the professional',
    '   crew rows required by the authority before submission.',
    '5. Passport / ID numbers are kept as text so leading zeros are preserved.',
    '',
    'The Greek authority provides no public API and no test environment, so the',
    'portal upload is the compliant submission path.',
  ];
  return { name: 'Instructions', rows: lines.map(l => [l]) };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Build the ordered list of sheets for the crew-manifest workbook. */
export function buildManifestSheets(
  charter: Charter,
  prep: ClientPreparation,
): XlsxSheet[] {
  return [
    personsSheet(charter, prep),
    charterInfoSheet(charter, prep),
    instructionsSheet(),
  ];
}

/** A safe, descriptive filename for the exported workbook. */
export function crewManifestFilename(charter: Charter): string {
  const base = (charter.name || charter.id || 'blueone')
    .replace(/[^a-z0-9]+/gi, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
  const date = charter.startDate || '';
  return `crew-manifest-${base}${date ? `-${date}` : ''}.xlsx`;
}

/** Build the workbook and trigger a browser download. */
export function downloadCrewManifestXlsx(
  charter: Charter,
  prep: ClientPreparation,
): void {
  const blob = buildXlsxBlob(buildManifestSheets(charter, prep));
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = crewManifestFilename(charter);
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 0);
}
